language: csharp
solution: core/Atlas.sln
dist: trusty
addons:
  sonarcloud:
    organization: dataart
    token:
      secure: ffbf078v1DdFbNmyVc2tfv3bBQ+UDlw9hLCrjc2gu9exAcmhvUluvhYPL6MGD+Xn3giMm6Dfn4oAbcrUTU000pewa/zGmH9Di9FBmXv8tzOMu6lJNHxsMqZCvFjI60eKFU+CknM4fTQNQ0jNEkS4ZSl5MwRQ/dAORAo6dQZOYSdfIe3x4jmBizEV/JIC5X7updUtiRJ8SK16vwzgy37hqLVt5zsADHRkLG2K3vsPcMMUMltGKEgGc5Dx78IzrZlH+AgfFhJcZSrLeCMTwpAAz9+9IYFbUeYDL+xU875+jbtvL2j6MpkH0Ls6D4AbGXGjuHPEW1qvOn5DiESVl50/DUmO5ilNnsnhicQ7cz/LTNYlys7Pn1bJOvHn1OZQD7huV0zEJXxOcRi4KCTWbYiYVKQoC4RSV4zPd2UvAAeL7Z035Y+KEQqezD/QHhTSU2AlvkHwZSwT45cbZClEZeYmJecmy1AqGuabZdSDGQ6KEFz2WBcHTZ67rIiEZrdDeiY0z/ikbmlQSiwlgO/uSBwS3N2Yw0HWSNr1Ag9dMxmbkIYNTts1OztCv6tXIR3yfAqlH0UT4af25Xpxwz+TzDFANSNuj+KA14h2wXR3KgU4q59G4KgtyIOhUcjNpL7sF5qURwjRULVD1eODBHxFObhREUvR3n3a3idSktbne+XCRSA=
script:
- sonar-scanner